# Generated by Django 6.0.6 on 2026-07-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_interest_profile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('friendship', 'Friendship'), ('relationship', 'Relationship')], max_length=20, null=True),
        ),
    ]
